### PR TITLE
fix: correct types for a JSON-ld context

### LINKED ISSUE #43: ldp_vc CredentialFormatProfile @context only allows string values
## What

When using the `ldp_vc` format and defining the `credentials_supported` in the issuer metadata, using a value for the `@context` that is not string, will result in an error being thrown (a vague one, but that should be fixed by #42?).

The credentials_supported entry. commenting the `@vocab` object will fix the error

```ts
{
  format: "ldp_vc",
  id: "OpenBadgeCredential",
  cryptographic_binding_methods_supported: ["did:web"],
  cryptographic_suites_supported: ["Ed25519Signature2018"],
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    {
      "@vocab": "https://w3id.org/security/undefinedTerm#",
    },
    "https://mattr.global/contexts/vc-extensions/v1",
    "https://purl.imsglobal.org/spec/ob/v3p0/context.json",
    "https://w3c-ccg.github.io/vc-status-rl-2020/contexts/vc-revocation-list-2020/v1.jsonld",
  ],
  types: [
    "VerifiableCredential",
    "VerifiableCredentialExtension",
    "OpenBadgeCredential",
  ],
}
```

The error:

```
{"code":1,"name":"Any","description":"invalid type: map, expected a string at line 1 column 678","additional_information":{"validation_message":"invalid type: map, expected a string at line 1 column 678"}}
```

### PR DESCRIPTION
**Pull request by blu3beri**
## Description

- `@context` field inside a JSON-LD object can now be: `list`,`map` and `string`.

## Related issue(s)

closes #43

## Checklist

- [ ] Tests (unit, integration and e2e where relevant)
- [ ] Documentation (in docs and within the code)

### CODE REVIEW

File: crates/openid4vci/src/types/credential.rs [hunk 1]
```diff
@@ -64,7 +78,7 @@ pub enum CredentialFormatProfile {
     LdpVc {
         /// JSON array as defined in [VC_DATA](https://www.w3.org/TR/vc-data-model/), Section 4.1.
         #[serde(rename = "@context")]
-        context: Vec<String>,
+        context: LinkedDataContext,
```
Comment (TimoGlastra) [inline crates/openid4vci/src/types/credential.rs:81]: > The value of the @context [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be an ordered set where the first item is a [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) with the value https://www.w3.org/2018/credentials/v1. For reference, a copy of the base context is provided in Appendix [B.1 Base Context](https://www.w3.org/TR/vc-data-model/#base-context). Subsequent items in the array MUST express context information and be composed of any combination of [URIs](https://www.w3.org/TR/vc-data-model/#dfn-uri) or objects


So I think this should be a `List<String | Map>` (or we could even go further and check that the first url is vc, but that's not really necessary I think)

Comment (TimoGlastra) [reply crates/openid4vci/src/types/credential.rs:81]: Couldn't we require a list that takes either string or map instead of adding another wrapper enum. It makes this code harded to call, which we could maybe just guard using normal types?

Comment (blu3beri) [reply crates/openid4vci/src/types/credential.rs:81]: No in Rust you cannot have an OR type and this is the common way of using different types for a single field.

Comment (blu3beri) [reply crates/openid4vci/src/types/credential.rs:81]: Will update with the new context. I checked the `json-ld` specification and that was a bit more loose.

Comment (blu3beri) [reply crates/openid4vci/src/types/credential.rs]: Should be fixed now.

**Review by TimoGlastra — APPROVED** [review]
One small comment, but otherwise LGTM
